"""block 0: initial schema

Revision ID: d796ad1b9ceb
Revises: 
Create Date: 2026-09-29 00:39:49.260357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd796ad1b9ceb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coverage_clauses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clause_id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('mechanism', sa.Text(), nullable=False),
    sa.Column('protected_block', sa.String(length=64), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coverage_clauses_clause_id'), 'coverage_clauses', ['clause_id'], unique=True)
    op.create_table('endpoints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.String(length=64), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('os_version', sa.String(length=255), nullable=False),
    sa.Column('collector_version', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_endpoints_agent_id'), 'endpoints', ['agent_id'], unique=True)
    op.create_table('missions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('source_text', sa.Text(), nullable=False),
    sa.Column('jir', sa.JSON(), nullable=False),
    sa.Column('jir_sha256', sa.String(length=64), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_missions_jir_sha256'), 'missions', ['jir_sha256'], unique=False)
    op.create_index(op.f('ix_missions_name'), 'missions', ['name'], unique=False)
    op.create_table('artifacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mission_id', sa.Integer(), nullable=False),
    sa.Column('variant_index', sa.Integer(), nullable=False),
    sa.Column('jir_hash', sa.String(length=64), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('llvm_ir_hash', sa.String(length=64), nullable=False),
    sa.Column('passes', sa.JSON(), nullable=False),
    sa.Column('equivalence_proven', sa.Boolean(), nullable=False),
    sa.Column('compiled_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artifacts_mission_id'), 'artifacts', ['mission_id'], unique=False)
    op.create_table('capability_decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mission_id', sa.Integer(), nullable=False),
    sa.Column('capability', sa.String(length=64), nullable=False),
    sa.Column('decision', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('jir_hash', sa.String(length=64), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_capability_decisions_capability'), 'capability_decisions', ['capability'], unique=False)
    op.create_index(op.f('ix_capability_decisions_mission_id'), 'capability_decisions', ['mission_id'], unique=False)
    op.create_table('evidence_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('endpoint_id', sa.Integer(), nullable=False),
    sa.Column('mission_id', sa.Integer(), nullable=True),
    sa.Column('finding_type', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('privileges', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('payload_sha256', sa.String(length=64), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('chain_index', sa.Integer(), nullable=False),
    sa.Column('prev_hash', sa.String(length=64), nullable=False),
    sa.Column('chain_hash', sa.String(length=64), nullable=False),
    sa.Column('capability', sa.String(length=64), nullable=False),
    sa.Column('signature', sa.String(length=256), nullable=False),
    sa.ForeignKeyConstraint(['endpoint_id'], ['endpoints.id'], ),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_records_chain_hash'), 'evidence_records', ['chain_hash'], unique=False)
    op.create_index(op.f('ix_evidence_records_endpoint_id'), 'evidence_records', ['endpoint_id'], unique=False)
    op.create_index(op.f('ix_evidence_records_finding_type'), 'evidence_records', ['finding_type'], unique=False)
    op.create_index(op.f('ix_evidence_records_mission_id'), 'evidence_records', ['mission_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evidence_records_mission_id'), table_name='evidence_records')
    op.drop_index(op.f('ix_evidence_records_finding_type'), table_name='evidence_records')
    op.drop_index(op.f('ix_evidence_records_endpoint_id'), table_name='evidence_records')
    op.drop_index(op.f('ix_evidence_records_chain_hash'), table_name='evidence_records')
    op.drop_table('evidence_records')
    op.drop_index(op.f('ix_capability_decisions_mission_id'), table_name='capability_decisions')
    op.drop_index(op.f('ix_capability_decisions_capability'), table_name='capability_decisions')
    op.drop_table('capability_decisions')
    op.drop_index(op.f('ix_artifacts_mission_id'), table_name='artifacts')
    op.drop_table('artifacts')
    op.drop_index(op.f('ix_missions_name'), table_name='missions')
    op.drop_index(op.f('ix_missions_jir_sha256'), table_name='missions')
    op.drop_table('missions')
    op.drop_index(op.f('ix_endpoints_agent_id'), table_name='endpoints')
    op.drop_table('endpoints')
    op.drop_index(op.f('ix_coverage_clauses_clause_id'), table_name='coverage_clauses')
    op.drop_table('coverage_clauses')
    # ### end Alembic commands ###
